//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rss_editor {
    
    
    public partial class AddNewsElement {
        
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        
        protected System.Web.UI.WebControls.XmlDataSource XmlDataSource1;
        
        protected System.Web.UI.WebControls.TextBox txtDate;
        
        protected System.Web.UI.WebControls.TextBox txtTitle;
        
        protected System.Web.UI.WebControls.TextBox txtDescr;
        
        protected System.Web.UI.WebControls.Button btnAdd;
        
        protected System.Web.UI.WebControls.GridView gvRSS;
        
        protected System.Web.UI.WebControls.Button btnDelEntry;
    }
}
